name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual runs

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check WakaTime API Key Presence
        run: |
          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
            echo "Secret WAKATIME_API_KEY is missing or empty!"
            exit 1
          else
            echo "Secret WAKATIME_API_KEY is set!"
          fi

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          REPOSITORY: AidanBilon/AidanBilon
          SECTION_NAME: waka
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
